### ISSUE TITLE
Incorrectly handling POST data

### ISSUE THREAD

**Issue by samperlmutter** [Yeti-Robotics/yeti-timesheet#1]
@rosswalk @James-koh
Referring to [addTeam.php](https://github.com/Yeti-Robotics/yeti-timesheet/blob/master/php/addTeam.php), normally using the `$_POST` variable would be correct, but by default the POSTs sent by angular are not stored in `$_POST` so you have to store the POST data in your own array using something like `$postData = json_decode(file_get_contents("php://input"), true);` which will store the input data in an associative array call `$postData`, then everywhere you would normally use `$_POST` you would use `$postData`.

**Comment by antoinecampbell** [comment]
We're doing things differently on this project, well be sending proper form
data instead if raw JSON.

**Comment by samperlmutter** [comment]
Alright, just making sure everyone's aware of angular's conventions.
